version: '3'

services:
  backend:
    build: ./
    container_name: hosting_container
    working_dir: /image-hosting
    command: ["./commands/start_server.sh"]
    ports:
      - "8010:8000"
    volumes:
      - ./src:/image-hosting/src
      - ./commands:/image-hosting/commands
      - static_volume:/image-hosting/src/static
      - media_volume:/image-hosting/src/media
    env_file:
      - ./src/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: hosting_postgres
    ports:
      - "5432:5432"
    volumes:
      - pd_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env

  nginx:
    image: nginx:1.19
    container_name: hosting_nginx
    volumes:
      - static_volume:/usr/share/nginx/html/static:ro
      - media_volume:/usr/share/nginx/html/media:ro
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend


volumes:
  static_volume:
  media_volume:
  pd_data: