# Generated by Django 5.2.3 on 2025-06-21 12:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        help_text="Original image file (JPG or PNG only)",
                        upload_to="images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="original file",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="file size",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="width"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="height"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageThumbnail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        help_text="Height of thumbnail in pixels (200, 400, etc.)",
                        verbose_name="size",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to="thumbnails/%Y/%m/%d/", verbose_name="thumbnail file"
                    ),
                ),
                ("width", models.PositiveIntegerField(verbose_name="width")),
                ("height", models.PositiveIntegerField(verbose_name="height")),
                ("file_size", models.PositiveIntegerField(verbose_name="file size")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="images.image",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Thumbnail",
                "verbose_name_plural": "Image Thumbnails",
                "ordering": ["size"],
            },
        ),
        migrations.CreateModel(
            name="TemporaryLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expires_in_seconds",
                    models.PositiveIntegerField(
                        help_text="Link expiration time in seconds (300-30000)",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(30000),
                        ],
                        verbose_name="expires in seconds",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                ("is_used", models.BooleanField(default=False, verbose_name="is used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_links",
                        to="images.image",
                        verbose_name="image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary Link",
                "verbose_name_plural": "Temporary Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["user", "-created_at"], name="images_imag_user_id_2b12b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["created_at"], name="images_imag_created_380b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagethumbnail",
            index=models.Index(
                fields=["image", "size"], name="images_imag_image_i_626a67_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="imagethumbnail",
            unique_together={("image", "size")},
        ),
        migrations.AddIndex(
            model_name="temporarylink",
            index=models.Index(
                fields=["expires_at", "is_used"], name="images_temp_expires_ee4742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="temporarylink",
            index=models.Index(
                fields=["user", "-created_at"], name="images_temp_user_id_cddaea_idx"
            ),
        ),
    ]
