# Generated by Django 5.2.3 on 2025-07-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageThumbnail",
        ),
    ]
