# Generated by Django 5.2.3 on 2025-06-20 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of tariff: Basic, Premium, Corporate or Custom",
                        max_length=50,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of tariff features",
                        max_length=1024,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Subscription price",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "is_built_in",
                    models.BooleanField(
                        default=False,
                        help_text="Built-in tariff (Basic, Premium, Enterprise)",
                        verbose_name="is built-in",
                    ),
                ),
                (
                    "has_thumbnail_200px",
                    models.BooleanField(
                        default=True,
                        help_text="Available thumbnail 200px",
                        verbose_name="has 200px thumbnail",
                    ),
                ),
                (
                    "has_thumbnail_400px",
                    models.BooleanField(
                        default=False,
                        help_text="Available thumbnail 400px",
                        verbose_name="has 400px thumbnail",
                    ),
                ),
                (
                    "has_original_photo",
                    models.BooleanField(
                        default=False,
                        help_text="Access to the original image size",
                        verbose_name="has original photo access",
                    ),
                ),
                (
                    "has_binary_link",
                    models.BooleanField(
                        default=False,
                        help_text="Ability to create temporary links",
                        verbose_name="has binary link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tariff Plan",
                "verbose_name_plural": "Tariff Plans",
                "ordering": ["price", "name"],
                "indexes": [
                    models.Index(fields=["price"], name="billing_tar_price_ba9bed_idx"),
                    models.Index(fields=["name"], name="billing_tar_name_d350cb_idx"),
                    models.Index(
                        fields=["is_built_in"], name="billing_tar_is_buil_f137d3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is the subscription active",
                        verbose_name="is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="billing.tariffplan",
                        verbose_name="subscription plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Tariff",
                "verbose_name_plural": "User Tariffs",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="billing_use_is_acti_4a4f42_idx"
                    ),
                    models.Index(
                        fields=["user"], name="billing_use_user_id_8fa124_idx"
                    ),
                    models.Index(
                        fields=["plan"], name="billing_use_plan_id_b5a67b_idx"
                    ),
                ],
            },
        ),
    ]
