# Generated by Django 5.2.3 on 2025-06-20 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSubscription",
            new_name="UserTariff",
        ),
        migrations.RenameIndex(
            model_name="usertariff",
            new_name="billing_use_is_acti_c5728b_idx",
            old_name="billing_use_is_acti_4a4f42_idx",
        ),
        migrations.RenameIndex(
            model_name="usertariff",
            new_name="billing_use_user_id_b27ab4_idx",
            old_name="billing_use_user_id_8fa124_idx",
        ),
        migrations.RenameIndex(
            model_name="usertariff",
            new_name="billing_use_plan_id_c31a6f_idx",
            old_name="billing_use_plan_id_b5a67b_idx",
        ),
    ]
