# Generated by Django 5.2.3 on 2025-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_tariffplan_price_alter_usertariff_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariffplan",
            name="paypal_plan_id",
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usertariff",
            name="paypal_subscription_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
