# Generated by Django 5.2.3 on 2025-07-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_tariffplan_paypal_plan_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertariff",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the subscription expires (null for Basic plan)",
                null=True,
                verbose_name="expires at",
            ),
        ),
    ]
