# Generated by Django 5.2.3 on 2025-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_usertariff_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertariff",
            name="expiration_notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
